export const env = {
  SITE_ORIGIN: process.env.SITE_ORIGIN!,
  JWT_SECRET: process.env.JWT_SECRET!,
  SMTP_PASS_RESTORE_PASSWORD: process.env.SMTP_PASS_RESTORE_PASSWORD!,
  SMTP_PASS_NOREPLY: process.env.SMTP_PASS_NOREPLY!,
  PASSWORD_PEPPER: process.env.PASSWORD_PEPPER!,
  TITORELLI_HOST: process.env.TITORELLI_HOST!
}
